-- https://school.programmers.co.kr/learn/courses/30/lessons/131533
-- title : 상품 별 오프라인 매출 구하기
-- created by haerin on 2023-05-31
SELECT PRODUCT_CODE, PRICE * SUM(SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE LEFT JOIN PRODUCT ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;