-- https://school.programmers.co.kr/learn/courses/30/lessons/133026
-- title : 성분으로 구분한 아이스크림 총 주문량
-- created by haerin on 2023-05-29
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF LEFT JOIN ICECREAM_INFO ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;