-- https://school.programmers.co.kr/learn/courses/30/lessons/131117
-- title : 5월 식품들의 총매출 조회하기
-- created by haerin on 2023-07-12
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, PRICE * AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT A
INNER JOIN (SELECT FOOD_ORDER.PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
FROM FOOD_ORDER
WHERE PRODUCE_DATE >= '2022-05-01' and PRODUCE_DATE <= '2022-05-31'
GROUP BY PRODUCT_ID) B 
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY 3 DESC, 1;