-- https://school.programmers.co.kr/learn/courses/30/lessons/131118
-- title : 서울에 위치한 식당 목록 출력하기
-- created by haerin on 2023-07-12
SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO A 
INNER JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE FROM REST_REVIEW GROUP BY REST_ID) B 
ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;