-- https://school.programmers.co.kr/learn/courses/30/lessons/164673
-- title : 조건에 부합하는 중고거래 댓글 조회하기
-- Created by haerin on 2023-05-17
SELECT TITLE, USED_GOODS_BOARD.BOARD_ID AS BOARD_ID, USED_GOODS_REPLY.REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD INNER JOIN USED_GOODS_REPLY ON USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
WHERE USED_GOODS_BOARD.CREATED_DATE >='2022-10-01' and USED_GOODS_BOARD.CREATED_DATE <='2022-10-31'
ORDER BY CREATED_DATE, TITLE;