-- https://school.programmers.co.kr/learn/courses/30/lessons/144855
-- title : 카테고리 별 도서 판매량 집계하기

SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK AS B INNER JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;