-- https://school.programmers.co.kr/learn/courses/30/lessons/131124
-- title : 그룹별 조건에 맞는 식당 목록 출력하기

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS M INNER JOIN REST_REVIEW AS R ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(REVIEW_ID) = (
        SELECT COUNT(REVIEW_ID)
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(REVIEW_ID) DESC
        LIMIT 1
    )
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;