-- https://school.programmers.co.kr/learn/courses/30/lessons/144856
-- title : 저자 별 카테고리 별 매출액 집계하기

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM (
    SELECT B.AUTHOR_ID, B.CATEGORY, (B.PRICE * S.SALES) AS TOTAL_SALES
    FROM BOOK AS B INNER JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
) AS B INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;