-- https://school.programmers.co.kr/learn/courses/30/lessons/157341
-- title : 대여 기록이 존재하는 자동차 리스트 구하기
-- created by haerin on 2023-06-19
SELECT DISTINCT(CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID) AS CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY LEFT JOIN CAR_RENTAL_COMPANY_CAR ON CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = CAR_RENTAL_COMPANY_CAR.CAR_ID
WHERE CAR_TYPE = '세단' and MONTH(START_DATE) = 10
ORDER BY CAR_ID DESC;