-- https://school.programmers.co.kr/learn/courses/30/lessons/59042
-- title : 없어진 기록 찾기
-- created by haerin on 2023-06-09
SELECT ANIMAL_OUTS.ANIMAL_ID AS ANIMAL_ID, ANIMAL_OUTS.NAME AS NAME
FROM ANIMAL_OUTS LEFT JOIN ANIMAL_INS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL
ORDER BY ANIMAL_OUTS.ANIMAL_ID;