-- https://school.programmers.co.kr/learn/courses/30/lessons/59411
-- title : 오랜 기간 보호한 동물(2)
-- created by haerin on 2023-06-09
SELECT ANIMAL_INS.ANIMAL_ID AS ANIMAL_ID, ANIMAL_INS.NAME AS NAME
FROM ANIMAL_INS INNER JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY (ANIMAL_OUTS.DATETIME - ANIMAL_INS.DATETIME) DESC
LIMIT 2;