-- https://school.programmers.co.kr/learn/courses/30/lessons/59043
-- title : 있었는데요 없었습니다
-- Created by haerin on 2023-06-09
SELECT ANIMAL_INS.ANIMAL_ID AS ANIMAL_ID, ANIMAL_INS.NAME AS NAME
FROM ANIMAL_INS LEFT JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
ORDER BY ANIMAL_INS.DATETIME;